baseURL = "http://example.org/"
languageCode = "en-us"
title = "Rose Quartz Foto"
theme = "sam"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    	dateform             = "Mon Jan 02, 2006"
    	dateformfull         = "Mon Jan 2 2006 15:04:05 EST"                                              
	favicon              = "favicon.ico"
    	homepage             = "Home"                           # What to call the home page link, link will not be rendered if empty    
	footerText           = "Rose Quartz Foto | Rosie McGowan"


#[[params.mainMenu]]
#	text = "Rose Quartz Foto | Rosie McGowan"

[[params.mainMenu]]
	link = "/photography"
	text = "I'm a photographer"

[[params.mainMenu]]
	link = "/design"
	text = "I'm a designer"

[[params.mainMenu]]
	link = "/music"
	text = "I'm a musician"	

[[params.mainMenu]]
	link= "/about"
	text = "I'm Rosie"

