baseURL = "https://rosiestquartz.github.io"
languageCode = "en-us"
title = "I'm Rosie"
theme = "sam"
publishDir = "../portfolio-public"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    	dateform             = "Mon Jan 02, 2006"
    	dateformfull         = "Mon Jan 2 2006 15:04:05 EST"                                              
	favicon              = "favicon.ico"
    	homepage             = "Home"                           # What to call the home page link, link will not be rendered if empty    
	footerText           = "RosiestQuartz | Rosie McGowan"


#[[params.mainMenu]]
#	text = "RosiestQuartz | Rosie McGowan"

[[params.mainMenu]]
	link = "/photography"
	text = "I'm a photographer"

#[[params.mainMenu]]
#	link = "/comingsoon"
#	text = "I'm a designer"

[[params.mainMenu]]
	link = "/comingsoon"
	text = "I'm a musician"	

[[params.mainMenu]]
	link= "/about"
	text = "I'm Rosie"

